# Generated by Django 6.1.1 on 2026-09-09 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100)),
                ('cliente_habitual', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
